### ISSUE TITLE
RethinkDB 2.0

### ISSUE THREAD

**Issue by AtnNn** [AtnNn/haskell-rethinkdb#44]
I updated the master branch to support RethinkDB 2.0.

Travis builds are failing because it is being run against 1.16, but tests on my machine pass on both GHC 7.6 and 7.8 against RethinkDB 2.0 RC1

I also updated the doctests to use the new `...` wildcard syntax.

**Comment by codedmart** [comment]
@AtnNn I pulled in your doctest changes to 1.16 and changed the version numbers. Can you do a 1.16 release so I can target that in my current project please.

**Comment by AtnNn** [comment]
@codedmart sure. However you put some of the some 2.0-specific changes into the 1.16 branch.

**Comment by codedmart** [comment]
@AtnNn oops, I checked your 1.16 changes to see which ones to pull and thought I cross checked all of them. Which ones?

**Comment by AtnNn** [comment]
Sorry, I diffed the wrong commits

**Comment by AtnNn** [comment]
The tests seem to pass https://travis-ci.org/AtnNn/haskell-rethinkdb/builds/55377096

I'll publish the 1.16 branch to hackage.

**Comment by codedmart** [comment]
Great, thanks!

**Comment by seanhess** [comment]
What can I do to help move this forward?

**Comment by codedmart** [comment]
@seanhess I believe this should be able to be released as is. There is a pr for 7.10 support #47 but is not necessary for 2.0. @AtnNn Can you confirm this is the case and/or push a 2.0 release please?

**Comment by seanhess** [comment]
@AtnNn Are you still maintaining this? I'm happy to assist if you are too busy, but I don't have rights to this repo or to hackage. How can I help?

**Comment by codedmart** [comment]
@seanhess I will try to get the 2.0 release in the next few days. Just a few things to bring together.

**Comment by seanhess** [comment]
@codedmart you have rights to everything? Cool. That'll work.

**Comment by codedmart** [comment]
Released https://github.com/AtnNn/haskell-rethinkdb/releases/tag/v2.0.0.0
