### ISSUE TITLE
Toggling TCP_NODELAY to reduce latency

### ISSUE THREAD

**Issue by nh2** [AtnNn/haskell-rethinkdb#55]
Hi, I'm just an innocent reader-by.

[Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle's_algorithm), which is on by default on most operating systems, can result in your packets being sent up to 40 ms after you write to a socket (e.g. the [`sendAll` you do here](https://github.com/AtnNn/haskell-rethinkdb/blob/4e09d7b9f2d9763969bcbd0bcf23c13ff0945fd9/Database/RethinkDB/Network.hs#L321)) when you must afterwards wait for a packet from the other side.

In other words, when you have a protocol where you send something and know that you now need to wait on a response from the other side, you should "flush" the TCP connection by disabling Nagle's algorithm ([toggling `TCP_NODELAY` on and off again](https://cloud-haskell.atlassian.net/browse/DP-108?focusedCommentId=17307&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17307)) in order to avoid a delay of up to 40 ms.

Are there places in this binding where you know that you'll have to wait for the other side to respond? If yes, this might be helpful.

Keep up the good work!

**Comment by nh2** [comment]
Sorry, this was sent to early.

What I meant to say is that instead of setting `TCP_NODELAY = 1` unconditionally (as you do [here](https://github.com/AtnNn/haskell-rethinkdb/blob/4e09d7b9f2d9763969bcbd0bcf23c13ff0945fd9/Database/RethinkDB/Network.hs#L125)), you can keep it off (keeping its throughput advantages) and turn it on only for those cases where you know you're done sending and now waiting for the other side to say something (thus avoiding its latency disadvantages).

My question is basically whether this would make sense for this binding, or whether it cannot be known ahead of time whether you are "done" sending or not.

**Comment by AtnNn** [comment]
It might make sense if you are sending a lot of small queries at once. But unless you are doing that and are running into performance problems, I would prefer not complicating the API.

**Comment by nh2** [comment]
As long as the library is careful with its `write()`/`writev()`/`send()`/`sendmsg()`/`sendmmsg()` calls (manifesting e.g. in ByteString's [`sendMany`](https://hackage.haskell.org/package/network-2.6.2.1/docs/Network-Socket-ByteString.html#v:sendMany)), keeping `TCP_NODELAY = 1` by default is a good default.

My toggling suggestion applies only if there are writes that cannot be controlled so well (each of those will result in an immediate send with `TCP_NODELAY).

Since I haven't actually observed any issues with this: Closing!

Thanks for taking a look at this!
