### ISSUE TITLE
Document why is `merge` flipped?

### ISSUE THREAD

**Issue by bitonic** [AtnNn/haskell-rethinkdb#56]
See https://github.com/AtnNn/haskell-rethinkdb/blob/3f7406fb6238f0f6ad93a143b0075bb2bb2bd7f0/Database/RethinkDB/Functions.hs#L520 . This goes against the normal rethinkdb API which states that

> When there is a conflict between field names, preference is given to fields in the rightmost object in the argument list.

**Comment by AtnNn** [comment]
This driver is based on the official JavaScript driver, you are correct to expect the same semantics. However the order of composition is flipped by putting the first argument last.

The JavaScript `a.merge(b)` corresponds in Haskell to `merge b $ a` just like `r.table("foo").get("bar")("baz")` corresponds to `(!"baz") . get "bar" $ table "foo"`.

**Comment by bitonic** [comment]
Thanks for the explanation.

1. Personally, I find this counter intuitive: when mimicking OOP in Haskell, I usually prefer putting the object to be modified always as the first argument.
2. Is this documented somewhere?

**Comment by AtnNn** [comment]
Although it feels a little weird for `merge`, this argument order makes a lot more sense for `pluck` and other functions, especially for `map`, `filter` and others whose namesake in the prelude have their arguments flipped compared to ReQL.

**Comment by codedmart** [comment]
@bitonic @AtnNn Do we need this open still?

**Comment by bitonic** [comment]
I guess not, although it'd be nice to have this (imo) surprising behavior documented

**Comment by codedmart** [comment]
@bitonic Fair enough. I changed the title of this issue so we can add some documentation as to why it is flipped. Thanks!

**Comment by codedmart** [comment]
closed via 24f4343282d3dda560f520ad1176ee6177017b26
