### ISSUE TITLE
Bump aeson

### ISSUE THREAD

**Issue by BardurArantsson** [AtnNn/haskell-rethinkdb#57]
aeson should probably be bumped again (and possibly 0.10.x should excluded explicitly!); see 

   http://permalink.gmane.org/gmane.comp.lang.haskell.cafe/119898

and especially the links therein.

**Comment by codedmart** [comment]
@BardurArantsson 0.10 works fine. I have tested. Was just bumping the aeson version when you filed this issue :). Closed in d3680fd.

**Comment by BardurArantsson** [comment]
There were multiple rather serious issues with 0.10.x it that you may not have discovered through casual testing. I just thought you might not be aware...

... but if you've *just* bumped, then I'm happy, regardless :).

Thanks!

**Comment by codedmart** [comment]
@BardurArantsson I can check the tests again, but I don't believe the issues affected us here. None the less I will release this bump shortly. Thanks for reporting!

**Comment by BardurArantsson** [comment]
Sure -- I'm not even aware how much your tests exercise aeson (or even how you're using it!), but thought I'd report just in case. :)

Thanks again,
