### ISSUE TITLE
Upsert

### ISSUE THREAD

**Issue by BardurArantsson** [AtnNn/haskell-rethinkdb#58]
(I hope it's OK to ask questions here. I'm not sure this is a bug.)

I'm trying to implement an "upsert" operation as in e.g. http://stackoverflow.com/a/21151469. 

Plopping the following JS into the console of my RethinkDB server seems to work:

```javascript
r.db('task_documents')
 .table('documents')
 .get('foo')
 .replace(function (doc) {
       return r.branch(
            doc.eq(null),
            { "id": "foo", "text": "bar" },
            doc.merge({ "id": "foo", "text": "second" }));
       })
```

On the first operation I correctly get "inserted: 1" back. Second I get "replaced: 1" and subsequent "unchanged: 1" (which is fine since it's a fixed document).

So far so good.

My equivalent Haskell looks like

```haskell
        let t = R.table "documents"
        response <- R.run' handle $ t #
            R.get "foo" #
              R.replace (\previousDocument ->
                           R.branch (previousDocument R.== R.Null)
                              (R.insert replacementDocument t)
                              (R.merge replacementDocument))
```

where `replacementDocument` is just some `Object ...` data structure. The details don't matter -- it does have an "id" key.

When I try to run the above against my RethinkDB instance I get the response

```
RethinkDB: Malformed query error: "Cannot nest writes or meta ops in stream operations.  Use FOR_EACH instead."
  in replace(
    get(table(db("task_documents"), "documents"), "ilqypvvqoxcgbygk"),
    (\b -> branch(
      eq(b, null),
      
        {- HERE -}
        insert(
          table(db("task_documents"), "documents"),
          {"aggregateState":...,"id":"ilqypvvqoxcgbygk"}),
      (\c -> merge(
        c,
        {"aggregateState":...,"id":"ilqypvvqoxcgbygk"})))))
```
(ellipsized slightly in the data objects for brevity)

Is my API usage incorrect or is there some sort of bug? The thing that sticks out is the explicit mention of the "table" in the `insert` operation whereas in the JS code, no table is explicitly mentioned.

(I'll try to see if I can get RethinkDB to log the full 'normalized' query for the JS version.)

**Comment by AtnNn** [comment]
@BardurArantsson the branches of your two queries are different:

Assuming you have `replacementDocument = ["id" := "foo", "text" := "bar"]`

The equivalent of the first branch, `{ "id": "foo", "text": "bar" }`, is `replacementDocument`

The equivalent of the second branch, `doc.merge({ "id": "foo", "text": "second" })`, is `previousDocument # merge replacementDocument`

If you have any other questions, you can ask on stackoverflow, irc or slack: https://www.rethinkdb.com/community/

**Comment by BardurArantsson** [comment]
Ah, one of those brain fart moments. Changing `R.insert replacementDocument t` to simply `replacementDocument` worked. I could have sworn I tried that...

Will ask one of the other places next time. (FTR, I did check the mailing list, but the Google search said that there wasn't a single mention of Haskell anywhere, so I didn't know where to turn.)

Thanks!
