### ISSUE TITLE
Durability is duplicated in RethinkDB.Functions and RethinkDB.Driver

### ISSUE THREAD

**Issue by cotrone** [AtnNn/haskell-rethinkdb#65]
Durability = Hard | Soft is duplicated in both [Database.RethinkDB.Driver](https://github.com/AtnNn/haskell-rethinkdb/blob/master/Database/RethinkDB/Driver.hs#L61) and [Database.RethinkDB.Functions](https://github.com/AtnNn/haskell-rethinkdb/blob/master/Database/RethinkDB/Functions.hs#L1032).

Should they be consolidated or are they separate for a reason?

Also, the constructors for durability aren't exported so you can't specify durability on a write/update etc.

I'm more than happy to help just need to know which direction to go in.

**Comment by AtnNn** [comment]
I think consolidating and exporting it is the right way to go.

**Comment by codedmart** [comment]
solved in 88479d21f56d1ef772d8cb3a3c89d1d2259cc83a
