### ISSUE TITLE
Default database for all queries

### ISSUE THREAD

**Issue by xiutxu** [AtnNn/haskell-rethinkdb#67]
How do you specify the database for the connection so that all your queries target the same database implicitly?

**Comment by codedmart** [comment]
@xiutxu you can use `use` for that:
https://github.com/AtnNn/haskell-rethinkdb/blob/31be0b101f3b4c9aa817113e706b79dea3538beb/Database/RethinkDB/Network.hs#L377-L380

**Comment by xiutxu** [comment]
Should I be using Stackoverflow for questions which pertain to this library?

**Comment by codedmart** [comment]
@xiutxu I am not sure if many people are answering haskell-rethinkdb questions on Stackoverflow, but you are welcome to ask. You can also ping me on the #rethinkdb irc channel and I can try and provide help.

**Comment by codedmart** [comment]
@xiutxu or the rethinkdb slack channel slack.rethinkdb.com.
