### ISSUE TITLE
Changefeeds?

### ISSUE THREAD

**Issue by user-three** [AtnNn/haskell-rethinkdb#70]
Will changefeeds be supported or are they supported and I just missed something?

**Comment by AtnNn** [comment]
Changefeeds are supported. See http://hackage.haskell.org/package/rethinkdb-2.2.0.8/docs/Database-RethinkDB.html#v:changes

**Comment by codedmart** [comment]
@user-three Please confirm if you have any other questions or if we can close this. Thanks!

**Comment by user-three** [comment]
Thank you very much!
